CREATE TABLE PRODUCT(
    PROD_ID INT PRIMARY KEY AUTO_INCREMENT, 	## PK (자동증가값)
    PROD_REGDATE TIMESTAMP DEFAULT NOW(), 	## 등록일 (기본값 시간형)
    PROD_ENDDATE VARCHAR(20),		## 판매종료일 (문자형 시간)
    PROD_CATEGORY VARCHAR(20),		## 카테고리 키
    PROD_WRITER VARCHAR(20),		## 작성자 FK
    PROD_NAME VARCHAR(300),  		## 상품명
    PROD_PRICE INT NOT NULL, 		## 가격
    PROD_COUNT INT NOT NULL, 		## 재고
    PROD_DISCOUNT INT DEFAULT 0, 		## 할인율 (기본값 숫자 0)
    PROD_PURCHASE_YN CHAR(1) DEFAULT 'N' CHECK (PROD_PURCHASE_YN IN ('Y', 'N')), ##체크제약
    PROD_CONTENT VARCHAR(5000), 	##내용()
    PROD_COMMENT VARCHAR(5000)		##메모
);

commit;

SELECT * FROM PRODUCT;

SELECT * FROM PRODUCT ORDER BY PROD_ID DESC LIMIT 0, 10; #데이터 시작 위치, 데이터 갯수
SELECT * FROM PRODUCT ORDER BY PROD_ID DESC LIMIT 10, 10;
SELECT * FROM PRODUCT ORDER BY PROD_ID DESC LIMIT 20, 10;
SELECT * FROM PRODUCT ORDER BY PROD_ID DESC LIMIT 0, 30; #1번부터 30개 뽑겠다라는 의미

CREATE TABLE TOPIC(
    TOPIC_ID INT PRIMARY KEY AUTO_INCREMENT, 	## PK (자동증가값)
    TOPIC_REGDATE TIMESTAMP, 	## 등록일 (기본값 시간형)
    TOPIC_WRITER VARCHAR(20),		## 작성자 FK
    TOPIC_NAME VARCHAR(300),  		## 게시글이름
    TOPIC_CONTENT VARCHAR(5000) 	## 내용()
);

SELECT * FROM TOPIC;

SELECT *
        FROM TOPIC
        WHERE TOPIC_WRITER = 'cutiepepe'
        ORDER BY TOPIC_ID DESC;

commit;

COMMIT;

SELECT *
FROM PRODUCT
WHERE PROD_NAME LIKE '%' || 'DEMO' || '%'
AND PROD_CONTENT LIKE '%33%';


CREATE TABLE PRODUCT_CATEGORY(
    CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT, ##카테고리 PK
    GROUP_ID VARCHAR(10),			##카테고리 대분류 그룹
    CATEGORY_LV INT, 				  ##1,2,3단
    CATEGORY_NM VARCHAR(100), 		##대분류 중분류 소분류
    CATEGORY_DETAIL_LV INT, 			##분류별 순서
    CATEGORY_DETAIL_NM VARCHAR(100), 		##이름
    CATEGORY_PARENT_LV INT , 			  ##1,2,3에 대한 부모컬럼
    CATEGORY_DETAIL_PARENT_LV INT		##분류별 순서에 대한 부모컬럼
);



############################################################################################################
#################################################데이터######################################################
## CTRL + SHIFT + 엔터

################첫번쨰 카테고리#################
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('A', 1, '대분류', 1, '패션뷰티', 0, 0);
       
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('A', 2, '중분류', 1, '여성패션', 1, 1);
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('A', 2, '중분류', 2, '남성패션', 1, 1);
       
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('A', 3, '소분류', 1, '의류', 2, 1);       
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('A', 3, '소분류', 2, '속옷/잠옷', 2, 1); 						
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('A', 3, '소분류', 3, '신발', 2, 1); 
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('A', 3, '소분류', 4, '잡화/가방', 2, 1); 

INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('A', 3, '소분류', 1, '(남)의류', 2, 2);       
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('A', 3, '소분류', 2, '(남)속옷/잠옷', 2, 2); 						
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('A', 3, '소분류', 3, '(남)신발', 2, 2); 
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('A', 3, '소분류', 4, '(남)잡화/가방', 2, 2); 


################두번쨰 카테고리#################
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 1, '대분류', 2, '가전디지털', 0, 0);

### 2단 데이터       
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 2, '중분류', 1, '생활가전', 1, 2);
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 2, '중분류', 2, '주방가전', 1, 2);
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 2, '중분류', 3, '데스크톱', 1, 2);

### 3단 데이터
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 3, '소분류', 1, '공기청정기', 2, 1);       
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 3, '소분류', 2, '다리미/재봉/보풀', 2, 1); 						
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 3, '소분류', 3, '비데/온수기', 2, 1); 
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 3, '소분류', 4, '전동칫솔/살균기', 2, 1); 

INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 3, '소분류', 1, '전기밥솥', 2, 2);       
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 3, '소분류', 2, '전자레인지', 2, 2); 						
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 3, '소분류', 3, '가스레인지', 2, 2); 
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 3, '소분류', 4, '냉장고', 2, 2); 
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 3, '소분류', 5, '식기세척기', 2, 2); 


INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 3, '소분류', 1, '브랜드', 2, 3);       
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 3, '소분류', 2, '일체형', 2, 3); 						
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 3, '소분류', 3, '조립', 2, 3); 
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('B', 3, '소분류', 4, '미니', 2, 3);
       
################세번쨰 카테고리#################  
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 1, '대분류', 3, '스포츠/레저', 0, 0);

### 2단 데이터       
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 2, '중분류', 1, '수영', 1, 3);
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 2, '중분류', 2, '골프', 1, 3);
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 2, '중분류', 3, '자전거', 1, 3);

### 3단 데이터
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 3, '소분류', 1, '실내수영복', 2, 1);       
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 3, '소분류', 2, '비치웨어/래쉬가드', 2, 1); 						
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 3, '소분류', 3, '수영용품', 2, 1); 
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 3, '소분류', 4, '물놀이용품', 2, 1); 

INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 3, '소분류', 1, '골프클럽', 2, 2);       
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 3, '소분류', 2, '골프백', 2, 2); 						
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 3, '소분류', 3, '골프웨어', 2, 2); 
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 3, '소분류', 4, '골프장갑', 2, 2); 
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 3, '소분류', 5, '골프화', 2, 2); 


INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 3, '소분류', 1, '자전거', 2, 3);       
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 3, '소분류', 2, '보호장비', 2, 3); 						
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 3, '소분류', 3, '악세사리', 2, 3); 
INSERT INTO PRODUCT_CATEGORY(GROUP_ID, CATEGORY_LV, CATEGORY_NM, CATEGORY_DETAIL_LV, CATEGORY_DETAIL_NM, CATEGORY_PARENT_LV, CATEGORY_DETAIL_PARENT_LV) 
	   VALUES ('C', 3, '소분류', 4, '자전거부품', 2, 3);
       
       
##########################################################################
SELECT A1.*,
       A2.CATEGORY_DETAIL_NM,
       A3.CATEGORY_DETAIL_NM
FROM PRODUCT_CATEGORY A1
LEFT OUTER JOIN PRODUCT_CATEGORY A2
ON A1.CATEGORY_PARENT_LV = A2.CATEGORY_LV AND A1.CATEGORY_DETAIL_PARENT_LV = A2.CATEGORY_DETAIL_LV AND A1.GROUP_ID = A2.GROUP_ID
LEFT OUTER JOIN PRODUCT_CATEGORY A3
ON A2.CATEGORY_PARENT_LV = A3.CATEGORY_LV AND A2.CATEGORY_DETAIL_PARENT_LV = A3.CATEGORY_DETAIL_LV
;


SELECT
  CONCAT(
    '● ', IFNULL(A3.CATEGORY_DETAIL_NM, '(ROOT)'), '\n',
    CASE WHEN A2.CATEGORY_DETAIL_NM IS NULL THEN '' ELSE '    └─ ' END,
    IFNULL(A2.CATEGORY_DETAIL_NM, ''), 
    CASE WHEN A2.CATEGORY_DETAIL_NM IS NULL THEN '' ELSE '\n' END,
    '        └─ ', A1.CATEGORY_DETAIL_NM
  ) AS tree_line
FROM PRODUCT_CATEGORY A1
LEFT JOIN PRODUCT_CATEGORY A2
  ON A1.CATEGORY_PARENT_LV = A2.CATEGORY_LV
 AND A1.CATEGORY_DETAIL_PARENT_LV = A2.CATEGORY_DETAIL_LV
 AND A1.GROUP_ID = A2.GROUP_ID
LEFT JOIN PRODUCT_CATEGORY A3
  ON A2.CATEGORY_PARENT_LV = A3.CATEGORY_LV
 AND A2.CATEGORY_DETAIL_PARENT_LV = A3.CATEGORY_DETAIL_LV
-- 필요시 정렬
ORDER BY A3.CATEGORY_DETAIL_NM, A2.CATEGORY_DETAIL_NM, A1.CATEGORY_DETAIL_NM;


SELECT CONCAT(A1.group_ID, A1.CATEGORY_ID) AS CATEGORY_KEY, ##카테고리 키 (그룹 + 키 형태로 카테고리분류)
 	     CASE A1.category_parent_LV WHEN 0 THEN A1.category_detail_NM
 			                            WHEN 1 THEN CONCAT(A2.category_detail_NM,' > ', A1.category_detail_NM)
                            			WHEN 2 THEN CONCAT(A3.category_detail_NM, ' > ', A2.category_detail_NM,' > ', A1.category_detail_NM)
			 END as CATEGORY_NAV
FROM PRODUCT_CATEGORY A1
LEFT OUTER JOIN PRODUCT_CATEGORY A2
ON A1.CATEGORY_PARENT_LV = A2.CATEGORY_LV AND A1.CATEGORY_DETAIL_PARENT_LV = A2.CATEGORY_DETAIL_LV AND A1.GROUP_ID = A2.GROUP_ID
LEFT OUTER JOIN PRODUCT_CATEGORY A3
ON A2.CATEGORY_PARENT_LV = A3.CATEGORY_LV AND A2.CATEGORY_DETAIL_PARENT_LV = A3.CATEGORY_DETAIL_LV
ORDER BY CATEGORY_NAV ASC;

SELECT * FROM PRODUCT WHERE PROD_cATEGORY IS NOT NULL;


SELECT * FROM PRODUCT_CATEGORY WHERE GROUP_ID = 'A' AND CATEGORY_PARENT_LV = 1 AND CATEGORY_DETAIL_PARENT_LV = 1;
SELECT * FROM PRODUCT_CATEGORY;

SELECT *
        FROM PRODUCT_CATEGORY
        WHERE CATEGORY_LV = 1;
        
        
COMMIT;

CREATE TABLE PRODUCT_CATEGORY(
    CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT, ##카테고리 PK
    GROUP_ID VARCHAR(10),			##카테고리 대분류 그룹
    CATEGORY_LV INT, 				  ##1,2,3단
    CATEGORY_NM VARCHAR(100), 		##대분류 중분류 소분류
    CATEGORY_DETAIL_LV INT, 			##분류별 순서
    CATEGORY_DETAIL_NM VARCHAR(100), 		##이름
    CATEGORY_PARENT_LV INT , 			  ##1,2,3에 대한 부모컬럼
    CATEGORY_DETAIL_PARENT_LV INT		##분류별 순서에 대한 부모컬럼
);


CREATE TABLE FARM_USER(
	USER_ID INT PRIMARY KEY AUTO_INCREMENT, ##사용자 고유 아이디
    USER_PW VARCHAR(15) NOT NULL,
    USER_NAME VARCHAR(25) NOT NULL,
    USER_PHONE VARCHAR(11) UNIQUE,
    USER_EMAIL VARCHAR(30) UNIQUE,
    AUTH VARCHAR(10) DEFAULT 'CONSUMER' CHECK ( AUTH IN ('ADMIN', 'CONSUMER'))
);

COMMIT;

SELECT * FROM FARM_USER;







    <insert id="prodRegist" parameterType="ProductVO">
        INSERT INTO PRODUCT(
                            PROD_ENDDATE,
                            PROD_CATEGORY,
                            PROD_WRITER,
                            PROD_NAME,
                            PROD_PRICE,
                            PROD_COUNT,
                            PROD_DISCOUNT,
                            PROD_PURCHASE_YN,
                            PROD_CONTENT,
                            PROD_COMMENT)
        VALUES (
                #{prodEnddate},
                #{prodCategory},
                #{prodWriter},
                #{prodName},
                #{prodPrice},
                #{prodCount},
                #{prodDiscount},
                #{prodPurchaseYn},
                #{prodContent},
                #{prodComment}
                )
    </insert>

<!--    파라미터 2개 이상이면 parameterType 생략-->
<!--    동적 쿼리 구문,
        if, choose, foreach가 있음
        if 구문의 test에는 getter명이 들어갈 수 있음.

-->
    <select id="getList" resultType="ProductVO">
        SELECT *
        FROM PRODUCT
        WHERE PROD_WRITER = #{prodWriter}
        <if test="cri.searchName != '' and cri.searchName != null ">
            AND PROD_NAME LIKE CONCAT('%', #{cri.searchName}, '%')
        </if>
        <if test="cri.searchContent != '' and cri.searchContent != null ">
            AND PROD_CONTENT LIKE CONCAT('%', #{cri.searchContent}, '%')
        </if>
        <if test="cri.startDate != '' and cri.startDate != null ">
            <![CDATA[
                    AND PROD_ENDDATE >= #{cri.startDate}
            ]]>
        </if>
        <if test="cri.endDate != '' and cri.endDate != null ">
            <![CDATA[
                    AND PROD_REGDATE <= #{cri.endDate}
            ]]>
        </if>
        ORDER BY
        <if test="cri.searchPrice == 'asc'">
            PROD_PRICE ASC,
        </if>
        <if test="cri.searchPrice == 'desc'">
            PROD_PRICE DESC,
        </if>
        PROD_ID DESC

        LIMIT #{cri.pageStart}, #{cri.amount}
    </select>

    <select id="getDetail" parameterType="long">
        SELECT *
        FROM PRODUCT
        WHERE PROD_ID = #{prodId}
    </select>

    <update id="prodUpdate" parameterType="ProductVO">
        UPDATE PRODUCT
        SET
            PROD_ENDDATE = #{prodEnddate},
            PROD_NAME = #{prodName},
            PROD_PRICE = #{prodPrice},
            PROD_COUNT = #{prodCount},
            PROD_DISCOUNT = #{prodDiscount},
            PROD_PURCHASE_YN = #{prodPurchaseYn},
            PROD_CONTENT = #{prodContent},
            PROD_COMMENT = #{prodComment}
        WHERE PROD_ID = #{prodId}
    </update>

    <delete id="prodDelete" parameterType="long">
        DELETE
        FROM PRODUCT
        WHERE PROD_ID = #{prodId}
    </delete>

    <select id="getTotal" resultType="int">
        SELECT COUNT(*)
            AS total
        FROM PRODUCT
        WHERE PROD_WRITER = #{prodWriter}
        <if test="cri.searchName != '' and cri.searchName != null ">
            AND PROD_NAME LIKE CONCAT('%', #{cri.searchName}, '%')
        </if>
        <if test="cri.searchContent != '' and cri.searchContent != null ">
            AND PROD_CONTENT LIKE CONCAT('%', #{cri.searchContent}, '%')
        </if>
        <if test="cri.startDate != '' and cri.startDate != null ">
            <![CDATA[
                    AND PROD_ENDDATE >= #{cri.startDate}
            ]]>
        </if>
        <if test="cri.endDate != '' and cri.endDate != null ">
            <![CDATA[
                    AND PROD_REGDATE <= #{cri.endDate}
            ]]>
        </if>
        <if test="cri.searchPrice == 'asc'">
            ORDER BY PROD_PRICE ASC,
        </if>
        <if test="cri.searchPrice == 'desc'">
            ORDER BY PROD_PRICE DESC,
        </if>
    </select>


<!--    // 대분류 조회-->
    <select id="getCategoryList" resultType="CategoryVO">
        SELECT *
        FROM PRODUCT_CATEGORY
        WHERE CATEGORY_LV = 1
    </select>
<!--    중~소분류 카테고리 조회-->
    <select id="getCategoryChildList" resultType="CategoryVO">
        SELECT *
        FROM PRODUCT_CATEGORY
        WHERE GROUP_ID = #{groupId}
          AND CATEGORY_PARENT_LV = #{categoryLv}
          AND CATEGORY_DETAIL_PARENT_LV = #{categoryDetailLv}
    </select>
</mapper>




SELECT CONCAT(A1.group_ID, A1.CATEGORY_ID) AS CATEGORY_KEY, ##카테고리 키 (그룹 + 키 형태로 카테고리분류)
 	     CASE A1.category_parent_LV WHEN 0 THEN A1.category_detail_NM
 			                            WHEN 1 THEN CONCAT(A2.category_detail_NM,' > ', A1.category_detail_NM)
                            			WHEN 2 THEN CONCAT(A3.category_detail_NM, ' > ', A2.category_detail_NM,' > ', A1.category_detail_NM)
			 END as CATEGORY_NAV
FROM PRODUCT_CATEGORY A1
LEFT OUTER JOIN PRODUCT_CATEGORY A2
ON A1.CATEGORY_PARENT_LV = A2.CATEGORY_LV AND A1.CATEGORY_DETAIL_PARENT_LV = A2.CATEGORY_DETAIL_LV AND A1.GROUP_ID = A2.GROUP_ID
LEFT OUTER JOIN PRODUCT_CATEGORY A3
ON A2.CATEGORY_PARENT_LV = A3.CATEGORY_LV AND A2.CATEGORY_DETAIL_PARENT_LV = A3.CATEGORY_DETAIL_LV
ORDER BY CATEGORY_NAV ASC;



SELECT * FROM PRODUCT WHERE PROD_CATEGORY IS NOT NULL;


SELECT * FROM PRODUCT_CATEGORY WHERE GROUP_ID = 'A' AND CATEGORY_PARENT_LV = 1 AND CATEGORY_DETAIL_PARENT_LV = 1;
SELECT * FROM PRODUCT_CATEGORY;

SELECT *
        FROM PRODUCT_CATEGORY
        WHERE CATEGORY_LV = 1;
        
        
-- PRODUCT 테이블의 PROD_CATEGORY와, CATEGORY 테이블의 CATEGORY_KEY를 조인해라--

SELECT *
FROM PRODUCT
WHERE PROD_WRITER = 'cutiepepe'
ORDER BY
PROD_ID DESC
LIMIT 0,10;

SELECT *
FROM PRODUCT AS P
LEFT JOIN PRODUCT_CATEGORY AS PC
ON P.PROD_CATEGORY = PC.PROD_CATEGORY



-- SELECT *
-- FROM PRODUCT P
-- LEFT JOIN (SELECT CONCAT(A1.group_ID, A1.CATEGORY_ID) AS CATEGORY_KEY,
--  	     CASE A1.category_parent_LV WHEN 0 THEN A1.category_detail_NM
--  			                            WHEN 1 THEN CONCAT(A2.category_detail_NM,' > ', A1.category_detail_NM)
--                             			WHEN 2 THEN CONCAT(A3.category_detail_NM, ' > ', A2.category_detail_NM,' > ', A1.category_detail_NM)
-- 			 END as CATEGORY_NAV
-- FROM PRODUCT_CATEGORY A1
-- LEFT OUTER JOIN PRODUCT_CATEGORY A2
-- ON A1.CATEGORY_PARENT_LV = A2.CATEGORY_LV AND A1.CATEGORY_DETAIL_PARENT_LV = A2.CATEGORY_DETAIL_LV AND A1.GROUP_ID = A2.GROUP_ID
-- LEFT OUTER JOIN PRODUCT_CATEGORY A3
-- ON A2.CATEGORY_PARENT_LV = A3.CATEGORY_LV AND A2.CATEGORY_DETAIL_PARENT_LV = A3.CATEGORY_DETAIL_LV
-- ORDER BY CATEGORY_NAV ASC) X
-- ON P.PROD_CATEGORY = X.CATEGORY_KEY
-- WHERE PROD_WRITER = 'ㅂㅈㄷㄱ'
-- ORDER BY P.PROD_ID DESC, X.CATEGORY_NAV ASC
-- LIMIT 0, 10;

SELECT *
FROM PRODUCT P
LEFT JOIN (
    SELECT 
        CONCAT(A1.group_ID, A1.CATEGORY_ID) AS CATEGORY_KEY,
        CASE A1.category_parent_LV
            WHEN 0 THEN A1.category_detail_NM
            WHEN 1 THEN CONCAT(A2.category_detail_NM,' > ', A1.category_detail_NM)
            WHEN 2 THEN CONCAT(A3.category_detail_NM, ' > ', A2.category_detail_NM,' > ', A1.category_detail_NM)
        END AS CATEGORY_NAV
    FROM PRODUCT_CATEGORY A1
    LEFT OUTER JOIN PRODUCT_CATEGORY A2
        ON A1.CATEGORY_PARENT_LV = A2.CATEGORY_LV
       AND A1.CATEGORY_DETAIL_PARENT_LV = A2.CATEGORY_DETAIL_LV
       AND A1.GROUP_ID = A2.GROUP_ID
    LEFT OUTER JOIN PRODUCT_CATEGORY A3
        ON A2.CATEGORY_PARENT_LV = A3.CATEGORY_LV
       AND A2.CATEGORY_DETAIL_PARENT_LV = A3.CATEGORY_DETAIL_LV
) X
ON P.PROD_CATEGORY = X.CATEGORY_KEY
WHERE P.PROD_WRITER = 'ㅂㅈㄷㄱ'
ORDER BY P.PROD_ID DESC, X.CATEGORY_NAV ASC
LIMIT 0, 10;


SELECT * FROM PRODUCT;


create table demo_order(
		oid int auto_increment primary key,
    mid int,
    product_name varchar(100)
);

insert into demo_order(mid, product_name) values(1, '상품1');
insert into demo_order(mid, product_name) values(1, '상품2');
insert into demo_order(mid, product_name) values(2, '상품3');


create table demo_member(
		mid int auto_increment primary key,
    name varchar(100)
);

insert into demo_member(name) values('홍길동');
insert into demo_member(name) values('이순신');

-- OID == PK
-- MID == FK
SELECT * FROM DEMO_ORDER;
SELECT * FROM DEMO_MEMBER;

-- N:1 JOIN
SELECT *
FROM DEMO_ORDER O
LEFT JOIN DEMO_MEMBER M
ON O.MID = M.MID;

-- 1:N JOIN
SELECT *
FROM DEMO_MEMBER M
LEFT JOIN DEMO_ORDER O
ON O.MID = M.MID
WHERE O.MID =1;

CREATE TABLE PRODUCT_UPLOAD (
	UPLOAD_NO INT PRIMARY KEY auto_increment,
	FILENAME varchar(100) not null, ##실제파일명
	FILEPATH varchar(100) not null, ##폴더명
	UUID varchar(50) not null, ##UUID명
	REGDATE TIMESTAMP default now(),
	PROD_ID INT, ##FK
	PROD_WRITER VARCHAR(20) ##FK
);

CREATE TABLE PRODUCT_UPLOAD (
	UPLOAD_NO INT PRIMARY KEY auto_increment,
	FILENAME varchar(100) not null, ##실제파일명
	FILEPATH varchar(100) not null, ##폴더명
	UUID varchar(50) not null, ##UUIaddressD명
	REGDATE TIMESTAMP default now(),
	PROD_ID INT, ##FK
	PROD_WRITER VARCHAR(20) ##FK
);

SELECT * FROM PRODUCT_UPLOAD;

COMMIT;

SELECT * FROM USERS;

SELECT * FROM ADDRESS;

SELECT ADDRESS, ADDRESS_NAME, RECIPIENT_NAME, RECIPIENT_PHONE
FROM ADDRESS WHERE USER_ID = 2;

CREATE TABLE ADDRESS (
    ADDRESS_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT UNSIGNED NOT NULL,
    ADDRESS VARCHAR(255),
    ADDRESS_NAME VARCHAR(20),
    RECIPIENT_NAME    VARCHAR(50)  NOT NULL,
	RECIPIENT_PHONE VARCHAR(20)  NOT NULL,
    PRIMARY KEY (ADDRESS_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

INSERT INTO ADDRESS(USER_ID, ADDRESS, ADDRESS_NAME, RECIPIENT_NAME, RECIPIENT_PHONE)
VALUES(1,'대지도 결실군 풍년면 만물로 77', '드론봇 농장', '농장주','010-1234-1234');

INSERT INTO ADDRESS (USER_ID, ADDRESS, ADDRESS_NAME, RECIPIENT_NAME, RECIPIENT_PHONE) VALUES
(2, '서울특별시 강남구 테헤란로 123, 101동 1203호', '집',        '김민수', '010-1234-0002'),
(3, '서울특별시 서초구 서초대로 77길 15, 502호',          '회사',      '이서연', '010-2345-0003'),
(4, '경기도 성남시 분당구 판교역로 235, C동 701호',       '집',        '박지훈', '010-3456-0004'),
(5, '서울특별시 마포구 월드컵북로 45, 3층',               '스튜디오',   '최수진', '010-4567-0005'),
(6, '부산광역시 해운대구 센텀중앙로 90, 1702호',           '집',        '정우진', '010-5678-0006'),
(2, '서울특별시 송파구 올림픽로 300, 리센츠 121동 802호',  '부모님집',  '김민수', '010-1234-0007'),
(3, '인천광역시 연수구 송도국제대로 168, 901호',           '집',        '이서연', '010-2345-0008'),
(4, '경기도 용인시 수지구 풍덕천로 11, 2층',               '사무실',     '박지훈', '010-3456-0009'),
(5, '대전광역시 유성구 대학로 99, B동 405호',              '기숙사A',    '최수진', '010-4567-0010'),
(6, '대구광역시 수성구 달구벌대로 2450, 801호',            '집',        '정우진', '010-5678-0011'),
(2, '광주광역시 서구 상무중앙로 7, 1004호',                '세컨드',     '김민수', '010-1234-0012'),
(3, '울산광역시 남구 삼산중로 100, 402호',                 '집',        '이서연', '010-2345-0013'),
(4, '경기도 고양시 일산서구 중앙로 1420, 1203호',          '원룸',      '박지훈', '010-3456-0014'),
(5, '경기도 부천시 길주로 210, 1502호',                    '집',        '최수진', '010-4567-0015'),
(6, '충청북도 청주시 상당구 남사로 45, 2층',               '창고',       '정우진', '010-5678-0016'),
(2, '경상남도 창원시 성산구 상남로 120, 703호',            '집',        '김민수', '010-1234-0017'),
(3, '강원특별자치도 춘천시 중앙로 12, 401호',             '별장',       '이서연', '010-2345-0018'),
(4, '제주특별자치도 제주시 연동 1234-5, 201호',            '휴가지',     '박지훈', '010-3456-0019'),
(5, '세종특별자치시 한누리대로 2000, 703호',                '집',        '최수진', '010-4567-0020');


commit;


CREATE TABLE SEC_USERS(
	USERNAME VARCHAR(30) PRIMARY KEY,
    PASSWORD VARCHAR(50) NOT NULL,
    ROLE VARCHAR(30)
);

ALTER TABLE SHOP
ADD COLUMN STATUS TINYINT AFTER PRICE;